@startuml

package "Frontend" {
  [Angular]
'  [Another Component]
}

[Angular] <--> HTTP


node "Backend" {
  [Spring Boot]
  [Spring Boot] <--> Hibernate
}

HTTP --> [Spring Boot]
Hibernate <--> [PostgreSQL]

database "PostgreSQL" {
}


@enduml
